config/routes.rb
Rails.application.routes.draw do
  resources :leagues do
    collection do
      get 'join'
      post 'join'
    end
  end
  resources :bets
  devise_for :users
  get 'welcome/index'

  resources :games do
    resources :bets
    resources :comments
  end

  get 'welcome/index'
  root 'welcome#index'

  resources :ranking

  

end

app/models/league.rb
class League < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_filter :authenticate_user!, only:[:index,:new,:show,:edit,:create,:update,:destroy]
  before_action :set_league, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, :except => [:show, :index]

  def authorize 
    redirect_to "/"
  end 


  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
    @leagues_user = League.find_by_sql("SELECT l.id, l.title FROM leagues l JOIN leagues_users lu ON l.id=lu.league_id WHERE lu.user_id="+current_user.id.to_s+";")
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @users = User.find_by_sql("SELECT u.username FROM users u JOIN leagues_users lu ON u.id=lu.user_id WHERE lu.league_id="+@league.id.to_s+";")
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  def join
    @pass = params[:pass] if params[:pass].present?
    @result = nil
    if (League.where(pass: @pass.to_i).take != nil)
      @league = League.where(pass: @pass.to_i).take
      if (League.count_by_sql("SELECT COUNT(*) FROM leagues_users WHERE league_id="+@league.id.to_s+" AND user_id="+current_user.id.to_s+";") != 0)
        @result = "Already in League !"
      else
        @query = "INSERT INTO leagues_users (league_id, user_id) VALUES ("+@league.id.to_s+","+current_user.id.to_s+");"
        League.connection.insert(@query)
        @result = "League joined !"
      end
    else
      if params[:pass].present?
        @result = "Wrong pass !"
      else
        @result = nil
      end
    end
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)
    @user = current_user
    @league.users << @user
    @league.pass = 0
    while ((@league.pass == 0) || (League.find_by pass: @league.pass != nil))
      @league.pass = Random.rand(999999)
    end

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:title, :description)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<<section id="hero">

 <div class="row">

   <div class="twelve columns">

     <div class="hero-text">
       <h1 class="responsive-headline">Edit League</h1>
       <p>Leagues are groups of friends</p>       
     </div>
     </br>

   </div>

 </div>

</section>
<section id="styles">
	<div class="row">
	  	<%= render 'form' %>
		<%= link_to 'Show', @league %> |
		<%= link_to 'Back', leagues_path %>
	</div>
</section>

app/views/leagues/index.html.erb
<section id="hero">

 <div class="row">

   <div class="twelve columns">

     <div class="hero-text">
       <h1 class="responsive-headline">Leagues</h1>
       <p>Leagues are groups of friends</p>       
     </div>
     </br>

   </div>

 </div>

</section>
<section id="styles">
  <div class="row">
    <h2 class="left">Your leagues :</h2>
    <%= link_to "<button id='newLeague' class='right'>Create a New League</button>".html_safe, new_league_path %>
    <%= link_to "<button id='newLeague' class='right'>Join a League</button>".html_safe, "/leagues/join" %> 
    <hr>
    <table class="fullTable">
    <% @leagues_user.each do |league_user| %>
    <tr>
      <td class="threeQuaterSize"> <%= league_user.title %> </td>
      <td> <%= link_to "<i class='fa fa-eye'></i>".html_safe, league_user %> </td>
      <td> <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_league_path(league_user) %> </td>
      <td> <%= link_to "<i class='fa fa-times'></i>".html_safe, league_user, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
    </tr>
    <%end%>
    </table>
  </div>

</section>

app/views/leagues/join.html.erb
<section id="hero">

 <div class="row">

   <div class="twelve columns">

     <div class="hero-text">
       <h1 class="responsive-headline">Join a League</h1>
       <p>Leagues are groups of friends</p>       
     </div>
     </br>
   </div>
 </div>
</section>
<section id="styles">
  <div class="row">
    <h3><%= @result %></h3>
    <%= form_tag("/leagues/join", method: "get") do %>
       <div class="field">
         <%= label_tag(:pass, "League's Pass :") %>
         <%= text_field_tag( :pass) %>
      </div>
      <div class="actions">
        <%= submit_tag("Join") %>
      </div>
    <% end %>
    <%= link_to "Back to leagues", leagues_path, :class => 'button' %>
  </div>
</section>

app/views/leagues/new.html.erb
<section id="hero">

 <div class="row">

   <div class="twelve columns">

     <div class="hero-text">
       <h1 class="responsive-headline">New League</h1>
       <p>Leagues are groups of friends</p>       
     </div>
     </br>

   </div>

 </div>

</section>
<section id="styles">
	<div class="row">
	  	<%= render 'form' %>

		<%= link_to 'Back', leagues_path %>
	</div>
</section>

app/views/leagues/show.html.erb
<section id="hero">

 <div class="row">

   <div class="twelve columns">

     <div class="hero-text">
       <h1 class="responsive-headline">League : <%= @league.title %></h1>
       <h2 class="responsive-headline"><%= @league.description %></h2>       
     </div>
     </br>

   </div>

 </div>

</section>
<section id="styles">
	<div class="row">
    <h2>Pass :</h2>
    <p><b><%= @league.pass %></b> - (This pass is required if people want to join your league, share it with your friends with caution !)</p>
    <hr>
		<h2>Member list :</h2>
		<% @users.each do |user| %>
      <%= user.username %>
      </br>
    <% end %>
    <hr>
    <%= link_to "Delete league".html_safe, @league, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</section>