config/routes.rb
Rails.application.routes.draw do
  resources :leagues do
    collection do
      get 'join'
      post 'join'
    end
  end
  resources :bets
  devise_for :users
  get 'welcome/index'

  resources :games do
    resources :bets
    resources :comments
  end

  get 'welcome/index'
  root 'welcome#index'

  resources :ranking

  

end

app/models/bet.rb
class Bet < ActiveRecord::Base
	belongs_to :game
	belongs_to :user
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_filter :authenticate_user!, only:[:new,:show,:edit,:create,:update,:destroy]
  before_action :set_bet, only: [:show, :edit, :update, :destroy]


  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.all
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
    if Bet.find_by(game_id: @bet.game_id, user_id: current_user.id)
      @game = Game.find(@bet.game_id)
      @access = true
    else
      @access = false
    end
  end

  # POST /bets
  # POST /bets.json
  def create
    @game = Game.find(params[:game_id])
    @bet = @game.bets.new(bet_params)
    @bet.user = current_user

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to "/games/"+@bet.game_id.to_s, notice: 'Bet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bet }
      else
        format.html { render :edit }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: 'Bet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:s1, :s2)
    end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for([@game, @bet]) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="row">
      <div class = "six columns betRight">
        <%= f.label @game.e1 %></br>
        <%= f.number_field :s1 , :value => @bet.s1 %>
      </div>
      <div class = "six columns betLeft">
        <%= f.label @game.e2 %></br>
        <%= f.number_field :s2 , :value => @bet.s2 %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<section id="hero">

 <div class="row">

   <div class="twelve columns">

     <div class="hero-text">
       <h1 class="responsive-headline"><%= @game.e1 %> VS <%= @game.e2 %></h1>
       <h2 class="responsive-headline"><%= @isPlayed %></h2>       
     </div>
     </br>

   </div>

 </div>
</section>
<section id="styles">
  <div class="row games">
    <div class="row">
      <div class="gameFlags">
        <% if @game.e1!="TBC" %>
         <%=  image_tag "flags/"+@game.e1 %>
        <% else %>
          <i class="fa fa-question fa-5x"></i>
        <% end %>
      </div>
      <div class="gameTitle">
      <h2><%= @game.e1 %> VS <%= @game.e2 %></h2>
      <p>
        <%= @game.description %></br>
        <i class="fa fa-clock-o"></i>   - <%= @game.start %></br>
        <i class="fa fa-map-marker"></i>   <%= @game.location %>
      </p>
      </div>
      <div class="gameFlags">
      <% if @game.e2!="TBC" %>
        <%= image_tag "flags/"+@game.e2 %>
      <% else %>
        <i class="fa fa-question fa-5x"></i>
      <% end %>
      </div>
    </div>
    <hr>
  </div>
  <div class="row gameBet">
  	<h2>Editing Bet</h2>
  	<% if @access == true %>
  		<%= render partial: 'bets/form' %>
  	<% else %>
  		<%= render file: "./public/404" %>
  	<% end %>
  	<%= link_to 'Back', :back, :class => 'button'%>
  </div>
</section>

app/views/bets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bets</h1>

<table>
  <thead>
    <tr>
      <th>Id game</th>
      <th>Id user</th>
      <th>S1</th>
      <th>S2</th>
      <th>Points</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.game_id %></td>
        <td><%= bet.user_id %></td>
        <td><%= bet.s1 %></td>
        <td><%= bet.s2 %></td>
        <td><%= bet.points %></td>
        <td><%= bet.done %></td>
        <td><%= link_to 'Show', bet %></td>
        <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
        <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<h1>New Bet</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>
<section id="styles">
  <div class="hero-text">
    <h1 id="titleBack">Your bet has been accounted</h1>
    <h2>Back to main in <span id="timer">5</span> second<span id="s">s</span></h2>
  </div>
</section>

<script type="text/javascript">
  
          var count = 5;
          var countdown = setInterval(function(){
            $("#timer").html(count);
            if(count==1)
            {
              $("#s").html("");
            }
            if (count == 0) {
              clearInterval(countdown);
              document.location.href= "/games";
            }
            count--;
          }, 1000);

</script>

<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>