config/routes.rb
Rails.application.routes.draw do
  resources :leagues do
    collection do
      get 'join'
      post 'join'
    end
  end
  resources :bets
  devise_for :users
  get 'welcome/index'

  resources :games do
    resources :bets
    resources :comments
  end

  get 'welcome/index'
  root 'welcome#index'

  resources :ranking

  

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :bets
	has_many :comments
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!, only:[:show,:edit,:create,:update,:destroy]
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, :except => [:show, :index ]

  def authorize 
    redirect_to "/"
  end 

  # GET /games
  # GET /games.json
  def index
    @games = Game.order(:id).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @isPlayed = "Not played"
    if @game.s2 != nil
      @isPlayed = @game.s1.to_s+" - "+@game.s2.to_s 
    end
    if Bet.find_by(game_id: @game.id, user_id: current_user.id)
      @betted = true
      @betDone = Bet.find_by(game_id: @game.id, user_id: current_user.id)
    else
      @betted = false
    end
    @bet = Bet.new
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end


  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        if @game.s1 > 0 || @game.s2 > 0
          bets = Bet.find_by_sql("SELECT * FROM bets WHERE game_id="+@game.id.to_s+";")
          bets.each do |bet|
            betPoints = 0
            if (@game.s1 > @game.s2 && bet.s1 > bet.s2) || (@game.s1 < @game.s2 && bet.s1 < bet.s2) 
              betPoints = 100
            end
            if (@game.s1 == @game.s2 && bet.s1 == bet.s2) || (@game.s1 == bet.s1 && @game.s2 == bet.s2)
              betPoints = 200
            end
            bet.points = betPoints.to_i
            bet.save
          end
        end
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:id, :description, :pool, :e1, :e2, :s1, :s2, :start, :end, :location)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :pool %><br>
    <%= f.text_field :pool %>
  </div>
  <div class="field">
    <%= f.label :e1 %><br>
    <%= f.text_field :e1 %>
  </div>
  <div class="field">
    <%= f.label :e2 %><br>
    <%= f.text_field :e2 %>
  </div>
  <div class="field">
    <%= f.label :s1 %><br>
    <%= f.number_field :s1 %>
  </div>
  <div class="field">
    <%= f.label :s2 %><br>
    <%= f.number_field :s2 %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.date_select :end %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<section id="hero">
  <div class="gameHead">

   <div class="row">

     <div class="twelve columns">

       <div class="hero-text">
         <h1 class="responsive-headline">Games</h1>
       </div>
       </br>

     </div>

   </div>
  </div>

</section>
<section id="styles">
  <% @games.each do |game| %>
  <div class="row games">
    <div class="gameFlags">
      <% if game.e1!="TBC" %>
       <%=  image_tag "flags/"+game.e1 %>
      <% else %>
        <i class="fa fa-question fa-5x"></i>
      <% end %>
    </div>
    <div class="gameTitle">
      <a href="./games/<%= game.id %>">
        <h2><%= game.e1 %> VS <%= game.e2 %></h2>
      </a>
      <p>
        <%= game.description %></br>
        Start time : <%= game.start %></br>
        <%= game.location %>
      </p>
    </div>
    <div class="gameFlags">
      <% if game.e2!="TBC" %>
        <%= image_tag "flags/"+game.e2 %>
      <% else %>
        <i class="fa fa-question fa-5x"></i>
      <% end %>
      </div>  
    <hr>
  </div>

  <% end %>
  <%= will_paginate @games, :class => 'pagination' %>
</section>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<section id="hero">
  <div class="gameHead">
   <div class="row">

     <div class="twelve columns">

       <div class="hero-text">
         <h1 class="responsive-headline"><%= @game.e1 %> VS <%= @game.e2 %></h1>
         <h1 class="responsive-headline"><%= @isPlayed %></h1>       
       </div>
       </br>

     </div>

   </div>
  </div>

</section>
<section id="styles">
  <div class="row games">
    <div class="row">
      <div class="gameFlags">
        <% if @game.e1!="TBC" %>
         <%=  image_tag "flags/"+@game.e1 %>
        <% else %>
          <i class="fa fa-question fa-5x"></i>
        <% end %>
      </div>
      <div class="gameTitle">
      <h2><%= @game.e1 %> VS <%= @game.e2 %></h2>
      <p>
        <%= @game.description %></br>
        <i class="fa fa-clock-o"></i> <%= @game.start.strftime("%m/%d/%Y at %I:%M%p UTC") %></br>
        <i class="fa fa-map-marker"></i> <%= @game.location %>
      </p>
      </div>
      <div class="gameFlags">
      <% if @game.e2!="TBC" %>
        <%= image_tag "flags/"+@game.e2 %>
      <% else %>
        <i class="fa fa-question fa-5x"></i>
      <% end %>
      </div>
    </div> 
    <hr>
  </div>
  <% if user_signed_in? %>
    <div class="row gameBet">
    <% if @betted==false && @isPlayed == "Not played" %>
      <%= render "bets/form" %>
    <% else %>  
      <h3>Your bet :</h3>
      <h4><%= @game.e1 %> <%= @betDone.s1 %> - <%= @betDone.s2 %> <%= @game.e2 %> </h4>
      <% if @betDone.points != nil %>
        <h5>You won <%= @betDone.points.to_s %> points !</h5> 
      <%else%>
        <%= link_to 'Edit your bet', edit_game_bet_path(@game.id, @betDone.id), :class => 'button'%>
      <% end %>
    <% end %>
    <hr>
    </div>
    <div class="row gameComments">
      <h2>Comments</h2>
      <% @game.comments.each do |comment| %>
        <p>
          <strong>Comment by <%= comment.user.username %> on <%= comment.created_at.strftime("%m/%d/%Y at %I:%M%p") %> :</strong>
          <%= comment.body %>
        </p>
      <% end %>
      <h2>New comment:</h2>
      <%= form_for([@game, @game.comments.build]) do |f| %>
        <p>
          <%= f.text_area :body %>
        </p>
        <p>
          <%= f.submit %>
        </p>
      <% end %>
    </div>
  <% else %>
    
  <% end %>
</section>